### ISSUE TITLE
Conduct comprehensive code review

### ISSUE THREAD

**Issue by helrond** [helrond/fornax#172]
## Is your feature request related to a problem? Please describe.
The code in this app has not been reviewed for a while, and with a fresh set of eyes, there are a number of things that could be improved.

## Describe the solution you'd like
Conduct a comprehensive code review of this application and address any issues. A couple of obvious things:
- Exception handling in the main `run` method could be improved - the custom exceptions aren't really all that useful
- places where variables are assigned to the instantiated class for no good reason (cleanup routine)
- places where existing asterism helpers could be used (helpers)
- Improve docstrings across application

**Comment by bonniegee** [comment]
Not sure if this should be a separate issue, but I think the fixtures (particularly those that represent JSON from Aurora) should be reviewed as well.
