### ISSUE TITLE
Parse "basis_note" not "note" from JSON

### ISSUE THREAD

**Issue by bonniegee** [helrond/fornax#180]
## Is your feature request related to a problem? Please describe.
Fornax is currently looking for "note" in rights JSON, but the field according to `rac_schemas` should be "basis_note"

## Describe the solution you'd like
Update the CsvCreator to look for "basis_note" instead of "note" and update fixtures as necessary.

We may need to look at "note" OR "basis_note" to deal with legacy Aurora data - does this sound right @helrond ?

## Additional context
Aquila is currently creating "note" instead of "basis_note"; this will be changed.

**Comment by helrond** [comment]
@bonniegee At this point we've updated Aurora rights statements so they're producing `basis_note` rather than `note`. I suppose if we really wanted to cover our bases we could check for both.

**Comment by bonniegee** [comment]
@helrond is Aurora also producing "granted_note" or is it producing "note"?

**Comment by helrond** [comment]
Right now Aurora is producing `note` in `rights_granted` but I'm gonna change that. RockefellerArchiveCenter/aurora#497
