### ISSUE TITLE
If an ingest is in process, the next SIP is marked as completed and sent to the cleanup service

### ISSUE THREAD

**Issue by bonniegee** [helrond/fornax#234]
## Describe the bug
In the StartPackageRoutine, there is a check to see whether there is already an ingest in progress in Archivematica before starting a transfer with the next SIP. Currently, if the check finds that there is an in-progress ingest, the SIP is saved with a process_status of APPROVED and is then picked up by the cleanup routine.

## To reproduce
Trigger the StartPackageRoutine while there is a PROCESSING ingest in Archivematica.

## Expected behavior
If another ingest is in process, the SIP process_status is set to ASSEMBLED so that it can try starting the transfer again.

## Additional context
@helrond , I'm inclined to not inherit from `BasePackage` to resolve this--do you have another approach?

**Comment by helrond** [comment]
I would be inclined to have that method raise a custom exception and then handle that in the BasePackageRoutine.
